//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoryWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryPage
    {
        public int historyId { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public string events { get; set; }
    }
}
